### ISSUE TITLE
LSQR not working for complex numbers

### ISSUE THREAD

**Issue by tknopp** [JuliaLang/IterativeSolvers.jl#32]
I tried to use the lsqr method on a complex system of equations and it did not work because several functions are not available for complex numbers (eps, isless).

**Comment by jiahao** [comment]
Thanks for the report. How urgently would you need this?

**Comment by tknopp** [comment]
Not urgent, I just wanted to play around with some alternative algorithms and found this bug.
I am currently using two algorithms that I have implemented on my own (Kaczmarz and CGNR) and I have in general thought weather these would fit into this package. But I have implemented them in a regularized fashion and on the normal equation.

**Comment by jiahao** [comment]
I think they would be nice additions to have especially if you have already implemented them and they work on some problem you are interested in. As @ViralBShah very wisely reminded me once, the perfect is the enemy of the good, so we might as well have code that is known to work on some problems as a starting point to make it more generically useful. CGNR is defined only on the normal equations anyway so I do not think that is a particularly onerous restriction.

**Comment by tknopp** [comment]
Yes, I was just not sure if all these algorithms can fit into a single package.

One serious issue is that the Kaczmarz algorithm cannot be implemented on column major matrices (memory access...). Thats why I implemented them in a transposed way...

**Comment by jiahao** [comment]
Do you have a reference for Kaczmarz (in English) I can look at? The Wikipedia article is not very informative, und mein Deutsch ist schlecht.

**Comment by tknopp** [comment]
:-) Well, http://www.eecs.berkeley.edu/~brecht/cs294docs/week1/09.Strohmer.pdf is informative. The algorithm is very simple

Kazcmarz method is basically SOR (successive over relaxation) on the normal equation. It sweeps row-wise through the matrix and forms in each (inner) iteration step the inner product of one matrix row with the right hand side. Thus, the no no to column major matrices.

I have talked to people that don't like the algorithm because it can be shown to converge infinitely slow on certain problems. In my use case it converges much faster than CGNR.

**Comment by jiahao** [comment]
@tknopp I have added randomized Kaczmarz to the list of randomized algorithms in #33.

**Comment by daanhb** [comment]
I have been using a complexified version of lsqr for quite a while, but only now noticed this issue. My routine is here:
https://github.com/daanhb/FrameFuns.jl/blob/master/src/my_lsqr.jl
It seems sufficient to invoke eps with just the T of Complex{T}, and to take the modulus (`abs`) a few times before comparing with isless.

This was implemented quickly by experimenting-and-fixing-errors, and so `my_lsqr` should definitely be considered a hack, but I plan to make a cleaner implementation since I'm interested in using this functionality. I'll read more of the IterativeSolvers code first to hopefully make it fit in better. I'm also interested in using `lsmr` since it works better for my application, so I might have a go at that as well.

**Comment by daanhb** [comment]
For completeness, I made a cleaner version of the `lsqr` routine I referenced before. It turns out that the difference with the real-only version is minimal. In particular, most variables are real and there is no need for a modulus anywhere, except for a single `abs2`.
