### ISSUE TITLE
rsvd giving wrong result when only one value is requested

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/IterativeSolvers.jl#42]
For more than value things seem to be fine. See
```jl
julia> srand(123);

julia> A = randn(10,2)*randn(2,10);

julia> [IterativeSolvers.rsvdvals(A, 1, 10)[1] - svdvals(A)[1] for i = 1:10]
10-element Array{Any,1}:
 -0.100009   
 -1.1555     
 -1.00972    
 -0.581412   
 -0.935978   
 -0.0789618  
 -0.0809019  
 -0.407415   
 -0.000799146
 -1.03752    

julia> [IterativeSolvers.rsvdvals(A, 2, 10)[1] - svdvals(A)[1] for i = 1:10]
10-element Array{Any,1}:
  0.0        
 -3.55271e-15
  0.0        
 -1.77636e-15
  0.0        
  1.77636e-15
  0.0        
 -3.55271e-15
  0.0        
  0.0  
```

**Comment by jiahao** [comment]
I'm convinced now that this behavior is expected. When you have only one random vector, you're essentially measuring its projection onto the range of `A`.

```jl
julia> Q = IterativeSolvers.rrange(A,1,p=10);
julia> B = Q' * A; svdvals(B)
1-element Array{Float64,1}:
 8.30363

julia> svdvals(A)[1:2]
2-element Array{Float64,1}:
 8.40364
 7.10549

julia> U = svd(A)[1]; W = Q'U
1x10 Array{Float64,2}:
 0.957606  0.288082  -2.06753e-17  -1.1404e-17  …  -5.987e-17  1.8414e-17  1.28096e-19
```

If we take `Q` to be a trial vector for the eigenvector of `AA'`, then its Ritz quotient is `Q'AA'Q = BB' = 68.9503`, which corresponds to an estimated singular value of A of `√(68.9603) = 8.30363`, which is exactly what is calculated.

Since in this example `A = u₁σ₁v₁ + u₂σ₂v₂` is of rank 2, the Ritz quotient can also be written as
`Q'(u₁σ₁²u₁' + u₂σ₂²u₂')Q = w₁²σ₁² + w₂²σ₂²`, which shows that it is simply taking a weighted contribution of the top two singular values, weighted by the projection coefficients of the random vector onto the true left singular vectors.

When there are two random vectors, they are linearly independent (with probability almost 1) and so must span the entire range of A, which is rank 2. Therefore `rsvdvals(A, 2, 10)` gives the exact answer.

**Comment by andreasnoack** [comment]
Asking for a single value-vector pair is not the same as restricting the size of the range approximation to  one. The documentation doesn't give many details about `p`, but from the reference ("Proto-algorithm", p. 224), I would expect the range approximation to have size `n+p`.

With a one pass range approximation, it would probably also be good to extend the warning such that it mentions that the singular pairs are probably plain wrong unless the matrix has rank less than `n` (or `n+p` if the range is extended as mentioned in the last paragraph).

**Comment by jiahao** [comment]
No, the reference recommends something like `k+p` where k is the number of desired singular values and `p` is the "slush factor".

Currently `rsvdvals` expects `k+p` as the second input. I could change it to require `k` and `p` separately, but then all it would do is compute `k+p` singular values and keep only `k`, which I think is a little silly implementation-wise. But maybe that would be what users want?

**Comment by andreasnoack** [comment]
First, so far I've assumed the `n` in `rsvd` corresponded to the `k` in the reference. I think `p` in `rsvd` is redundant in the present implementation.

> but then all it would do is compute k+p singular values and keep only k, which I think is a little silly implementation-wise.

Isn't this similar to Lanczos methods where you compute more subspace vectors (and therefore singular/eigenvalues) than asked for in order to compute those returned precisely enough?

> But maybe that would be what users want?

I think the user would like reasonable approximations to the top singular pairs. Right now they won't get that.
```jl
julia> A = randn(10,10);

julia> rsvd(A, 3)[:S] - svdvals(A)[1:3]
3-element Array{Float64,1}:
 -0.163552
 -1.09701 
 -0.86312 
```

**Comment by jiahao** [comment]
> Isn't this similar to Lanczos methods where you compute more subspace vectors (and therefore singular/eigenvalues) than asked for in order to compute those returned precisely enough?

If you're trying to draw a 1-1 correspondence between Lanczos vectors and the vectors being computed by rsvd, then yes. However, svd computation underneath rsvd is not iterative and we don't really have a good theory for error bounds in the randomized methods. In Lanczos we at least know which vectors are converged.

> I think the user would like reasonable approximations to the top singular pairs. Right now they won't get that.

That is the algorithm's fault, not the implementation's. I'm convinced that the algorithm as described simply cannot deliver reasonable approximations without effectively exhausting the entire range of `A`. At the moment the only thing the reference tells you to do is "increase `p` until you get the  answer you want.

**Comment by jiahao** [comment]
Or maybe I can rename `rsvd*` to `rsvd*_simple` and make clear that none of the implementations are really meant for black box use.

We can replace `rsvd` with our translation of [FastPCA](http://biorxiv.org/content/early/2015/04/16/018143), which is the only description of a randomized SVD with sane defaults that a user can use without thinking too hard.

**Comment by andreasnoack** [comment]
> That is the algorithm's fault, not the implementation's. I'm convinced that the algorithm as described simply cannot deliver reasonable approximations without effectively exhausting the entire range of `A`.

1. *Implementation*: Increasing the `p` in `rsvd` won't help because it doesn't affect the size of the range approximation
2. *Algorithm*: I agree that the it is not good for computing singular pairs, but therefore
3. *Documentation*: there is already a warning, but it gives the impression that the returned pairs are singular pairs, which they most often are not. I think it is problematic to have a function that most often produces garbage in Julia's main package for "truncated" solvers. This is the only reason why I am complaining here.

**Comment by andreasnoack** [comment]
> We can replace rsvd with our translation of FastPCA, which is the only description of a randomized SVD with sane defaults that a user can use without thinking too hard.

Some kind of iterative scheme to make sure the results are somewhat precise would be better. Then people would get correct results while realizing that these methods are quite slow.

**Comment by jiahao** [comment]
> Implementation: Increasing the p in rsvd won't help because it doesn't affect the size of the range approximation

Oh, I see the problem now. I read the original reference as saying that the extra `p` vectors are used only to refine the randomized basis Q (of `k` vectors) and that the `p` extra vectors are not used to construct the projected matrix `Q'A`. That doesn't make any sense because all the extra vectors are doing now is refining the orthogonality of the `k` vectors of Q before it is used for projection and then they get thrown away before the actual SVD calculation.

That part of the implementation can be fixed, at least.
