### ISSUE TITLE
svdl gives inaccurate results on top singular value/vector

### ISSUE THREAD

**Issue by madeleineudell** [JuliaLang/IterativeSolvers.jl#55]
For small problem sizes, svdl gives very inaccurate estimates of the top singular vector and value when only the top singular tuple is requested:

julia> A = randn(10,12);

julia> u,s,v = svd(A);

julia> usv, pf = svdl(A, 1, vecs=:both);

julia> usv.S - s[1]
1-element Array{Float64,1}:
 -0.254325

julia> usv.U - u[:,1]
10x1 Array{Float64,2}:
 -0.267003
  0.0976195
  0.103981
  0.104208
  0.053799
 -0.0442081
 -0.0124698
  0.0776354
  0.0219778
  0.091303

**Comment by andreasnoack** [comment]
I can confirm that this is still a problem on master.

**Comment by poulson** [comment]
:100:

**Comment by jiahao** [comment]
svdl uses two different estimates for the error on the singular values, one of which uses an estimate for the spectral gap making use of the fact that the Ritz value is variational. Since there is no estimate of the spectral gap when only one singular value is requested, the error bar predicted using the latter method is always erroneously calculated to be 0. The solution here is to never use the variationally derived error estimate if only one singular value is requested.
